variables:
    AWS_ACCESS_KEY_ID: «KEY»
    AWS_SECRET_ACCESS_KEY: «KEY»
    S3_BUCKET: «BUCKET»

stages:
    - build
    - deploy

build react-app:
    image: node:latest
    stage: build
    only:
        - master
    script:
        - export PATH=$PATH:/usr/bin/npm
        - npm install
        - CI=false npm run build
    artifacts:
        paths:
            - build/
        expire_in: 1 hour

deploy master:
    image: python:latest
    stage: deploy
    only:
        - master
    script:
        - pip3 install awscli
        - aws s3 sync ./build s3://$S3_BUCKET --acl public-read
